### ISSUE TITLE
Нет вывода товаров по акции

### ISSUE THREAD

**Issue by BaMnu** [BaMnu/team-work-grocery-helper#2]
Необходимо добавить строку вывода товара по акции, убрать лишнюю инициализацию String'а на 33 строке , также обрати внимание на формат кода и лишние пустые строки (с 69 по 75 строки посмотри)
**String text;**
 
- [ ] Добавить вывод товара по акции - между 27 и 28 строкой;
- [ ] Заменить _String text = "";_ на -> **String text;** в 33 строке
- [ ] Убрать пустые строки 69, 72, 74
- [ ] Реформатировать код - Code -> Reformat code в идее

https://github.com/BaMnu/team-work-grocery-helper/blob/9afab760a666c6a0078175e4fa2f103192c72eb7/src/Main.java#L23-L28

https://github.com/BaMnu/team-work-grocery-helper/blob/9afab760a666c6a0078175e4fa2f103192c72eb7/src/Main.java#L33

https://github.com/BaMnu/team-work-grocery-helper/blob/9afab760a666c6a0078175e4fa2f103192c72eb7/src/Main.java#L69-L75

**Comment by KosNet75** [comment]
Исправленно
